
spring:
  application:
    name: gateway-service
  cloud:
    config:
      uri: http://localhost:8082
  config:
    import: configserver:http://localhost:8082
server:
  port: 1443

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/

